### ISSUE TITLE
reason why courses-ci is failing

### ISSUE THREAD

**Issue by cutthroat78** [LibreLingo/LibreLingo-OcAuvSept-from-FR#2]
The reason why courses-ci is failing is because the target language in the mini-dictionary of each skill is defined as "Occitan Bas-Auvergnat" and not "Occitan"

Going through each skill and replacing "Occitan Bas-Auvergnat" with "Occitan", should resolve the problem

You set what the target language is in the course.yaml at:
```
Course:
  Language:
    Name: Occitan
```

I hope this helps

**Comment by PrWalterB** [comment]
Thanks ! I've fixed that
